worker_processes 1;
pid /tmp/nginx.pid;
error_log /dev/stderr notice;

events {
    worker_connections 128;
}

stream {
    upstream host_postgres_socket {
        server unix:/run/schemii-host-postgres/.s.PGSQL.5432;
    }

    server {
        listen 127.0.0.1:5432;
        proxy_connect_timeout 5s;
        proxy_timeout 3600s;
        proxy_pass host_postgres_socket;
    }
}
