-- Canonical target-database seed for the resettable Schemii demo fixture.
-- Named test alterations live under demo-scenarios/ and run only after the
-- application has imported this baseline into metadata.
\set ON_ERROR_STOP on

BEGIN;
SELECT pg_advisory_xact_lock(hashtext('schemii:test-seed:migration-demo')::bigint);
SELECT to_regclass('public.teams') IS NULL AS install_demo \gset
\if :install_demo

CREATE TYPE public.task_status AS ENUM ('backlog', 'ready', 'active', 'blocked', 'done');
CREATE TYPE public.project_visibility AS ENUM ('private', 'team', 'public');

CREATE SCHEMA schemii_fixture;
CREATE TABLE schemii_fixture.fixture_state (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    scenario text NOT NULL,
    source_revision text NOT NULL,
    fixture_digest char(64) NOT NULL CHECK (fixture_digest ~ '^[0-9a-f]{64}$'),
    workspace_id text NOT NULL CHECK (workspace_id ~ '^ws_[0-9a-f]{32}$'),
    reset_at timestamp with time zone NOT NULL DEFAULT clock_timestamp()
);

COMMENT ON SCHEMA schemii_fixture IS
    'Launcher-owned provenance for the isolated Schemii demo database.';

CREATE TABLE public.teams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL UNIQUE,
    slug varchar(80) NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9-]+$'),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
    email varchar(255) NOT NULL UNIQUE,
    display_name varchar(120) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
    owner_id bigint NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    name varchar(160) NOT NULL,
    code varchar(12) NOT NULL,
    visibility public.project_visibility NOT NULL DEFAULT 'team',
    budget numeric(12,2) CHECK (budget >= 0),
    starts_on date,
    ends_on date,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (team_id, code),
    CHECK (ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on)
);

CREATE TABLE public.tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    assignee_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
    parent_task_id bigint REFERENCES public.tasks(id) ON DELETE SET NULL,
    title varchar(240) NOT NULL,
    description text,
    status public.task_status NOT NULL DEFAULT 'backlog',
    priority smallint NOT NULL DEFAULT 3 CHECK (priority BETWEEN 1 AND 5),
    estimate_hours numeric(7,2) CHECK (estimate_hours >= 0),
    due_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CHECK ((status = 'done') = (completed_at IS NOT NULL))
);

CREATE TABLE public.task_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
    author_id bigint NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    body text NOT NULL CHECK (length(body) > 0),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    edited_at timestamp with time zone
);

CREATE TABLE public.tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
    name varchar(50) NOT NULL,
    color char(7) NOT NULL DEFAULT '#8b5cf6' CHECK (color ~ '^#[0-9a-fA-F]{6}$'),
    UNIQUE (team_id, name)
);

CREATE TABLE public.task_tags (
    task_id bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, tag_id)
);

-- Intentionally empty. Saved demo scenarios use this relation to prove that
-- PostgreSQL can accept a new required column without inventing population
-- data, while populated relations remain protected by migration planning.
CREATE TABLE public.empty_migration_lab (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label varchar(40) NOT NULL
);

-- A deliberately isolated write target for the SQL Console demo. Resetting the
-- fixture restores this row, so commit and rollback exercises are repeatable.
CREATE TABLE public.console_demo_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_key varchar(80) NOT NULL UNIQUE,
    note text NOT NULL,
    change_count integer NOT NULL DEFAULT 0 CHECK (change_count >= 0),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX projects_team_created_idx ON public.projects (team_id, created_at DESC);
CREATE INDEX tasks_project_status_priority_idx ON public.tasks (project_id, status, priority);
CREATE INDEX tasks_assignee_due_idx ON public.tasks (assignee_id, due_at) WHERE assignee_id IS NOT NULL;
CREATE INDEX task_comments_task_created_idx ON public.task_comments (task_id, created_at);
CREATE INDEX users_preferences_gin_idx ON public.users USING gin (preferences);

INSERT INTO public.teams (id, name, slug) VALUES
    (1, 'Orbit Labs', 'orbit-labs'),
    (2, 'Northwind Studio', 'northwind-studio');

INSERT INTO public.users (id, team_id, email, display_name, preferences) VALUES
    (1, 1, 'ava@orbit.test', 'Ava Chen', '{"theme":"dark","digest":true}'),
    (2, 1, 'marcus@orbit.test', 'Marcus Reed', '{"theme":"dark","digest":false}'),
    (3, 1, 'ines@orbit.test', 'Ines Silva', '{"theme":"system"}'),
    (4, 2, 'noah@northwind.test', 'Noah Williams', '{"theme":"light"}');

INSERT INTO public.projects (id, team_id, owner_id, name, code, visibility, budget, starts_on, ends_on) VALUES
    (1, 1, 1, 'Migration Workbench', 'MIGRATE', 'team', 85000.00, '2026-08-01', '2026-12-15'),
    (2, 1, 2, 'Mobile Refresh', 'MOBILE', 'private', 42000.00, '2026-09-01', NULL),
    (3, 2, 4, 'Analytics Portal', 'ANALYTICS', 'public', 125000.00, '2026-07-15', '2027-02-28');

INSERT INTO public.tasks (id, project_id, assignee_id, parent_task_id, title, description, status, priority, estimate_hours, due_at, completed_at) VALUES
    (1, 1, 1, NULL, 'Establish catalog baseline', 'Capture the initial server-owned schema snapshot.', 'done', 1, 6.00, '2026-08-04 16:00+00', '2026-08-04 14:20+00'),
    (2, 1, 2, NULL, 'Review generated migration SQL', 'Confirm dependency ordering and destructive warnings.', 'active', 1, 10.50, '2026-09-05 17:00+00', NULL),
    (3, 1, 3, 2, 'Exercise external drift conflict', NULL, 'ready', 2, 4.00, '2026-09-07 17:00+00', NULL),
    (4, 2, 2, NULL, 'Polish mobile table inspector', NULL, 'blocked', 2, 14.00, '2026-09-12 17:00+00', NULL),
    (5, 3, 4, NULL, 'Model reporting dimensions', NULL, 'backlog', 3, 18.00, NULL, NULL);

INSERT INTO public.task_comments (task_id, author_id, body) VALUES
    (2, 1, 'The SQL preview should be identical to the statement the server executes.'),
    (2, 2, 'Added checks for compatible and conflicting external changes.'),
    (4, 3, 'Waiting on the compact inspector interaction review.');

INSERT INTO public.tags (id, team_id, name, color) VALUES
    (1, 1, 'database', '#38bdf8'),
    (2, 1, 'migration', '#a78bfa'),
    (3, 1, 'mobile', '#34d399'),
    (4, 2, 'analytics', '#f59e0b');

INSERT INTO public.task_tags (task_id, tag_id) VALUES
    (1, 1), (1, 2), (2, 2), (3, 1), (3, 2), (4, 3), (5, 4);

INSERT INTO public.console_demo_notes (id, scenario_key, note, change_count, updated_at)
VALUES (1, 'transaction-demo', 'Reset baseline', 0, '2026-09-01 12:00:00+00');

SELECT setval(pg_get_serial_sequence('public.teams', 'id'), 2);
SELECT setval(pg_get_serial_sequence('public.users', 'id'), 4);
SELECT setval(pg_get_serial_sequence('public.projects', 'id'), 3);
SELECT setval(pg_get_serial_sequence('public.tasks', 'id'), 5);
SELECT setval(pg_get_serial_sequence('public.task_comments', 'id'), 3);
SELECT setval(pg_get_serial_sequence('public.tags', 'id'), 4);
SELECT setval(pg_get_serial_sequence('public.console_demo_notes', 'id'), 1);

\endif
COMMIT;

DO $$
BEGIN
    IF (SELECT count(*) FROM public.tasks) <> 5
       OR (SELECT count(*) FROM public.task_comments) <> 3
       OR (SELECT count(*) FROM public.console_demo_notes) <> 1 THEN
        RAISE EXCEPTION 'Schemii migration demo seed is incomplete';
    END IF;
END
$$;
