\set ON_ERROR_STOP on

-- Mercury Books is the archived Schemii tutorial domain, installed directly at
-- its final catalog shape for this disposable test deployment.
-- Increment each schema's fixture version when its catalog shape changes.
BEGIN;
SELECT pg_advisory_xact_lock(hashtext('schemii:test-seed:bookstore')::bigint);
SELECT to_regnamespace('bookstore') IS NULL AS install_bookstore \gset
\if :install_bookstore
CREATE SCHEMA bookstore;
COMMENT ON SCHEMA bookstore IS 'Schemii seeded Mercury Books test dataset; fixture=v1';

CREATE TABLE bookstore.publishers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL UNIQUE,
    country_code char(2) NOT NULL CHECK (country_code ~ '^[A-Z]{2}$'),
    founded_year integer CHECK (founded_year BETWEEN 1400 AND 2100)
);

CREATE TABLE bookstore.authors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    email varchar(255) UNIQUE,
    country_code char(2),
    biography text
);

CREATE TABLE bookstore.books (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id bigint NOT NULL REFERENCES bookstore.publishers(id) ON DELETE RESTRICT,
    isbn char(13) NOT NULL UNIQUE CHECK (isbn ~ '^[0-9]{13}$'),
    title varchar(240) NOT NULL,
    published_on date,
    price numeric(10,2) NOT NULL CHECK (price >= 0),
    format varchar(20) NOT NULL CHECK (format IN ('hardcover', 'paperback', 'ebook')),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE bookstore.book_authors (
    book_id bigint NOT NULL REFERENCES bookstore.books(id) ON DELETE CASCADE,
    author_id bigint NOT NULL REFERENCES bookstore.authors(id) ON DELETE CASCADE,
    author_order smallint NOT NULL DEFAULT 1 CHECK (author_order > 0),
    PRIMARY KEY (book_id, author_id),
    UNIQUE (book_id, author_order)
);

CREATE TABLE bookstore.inventory (
    book_id bigint PRIMARY KEY REFERENCES bookstore.books(id) ON DELETE CASCADE,
    on_hand integer NOT NULL DEFAULT 0 CHECK (on_hand >= 0),
    reorder_level integer NOT NULL DEFAULT 5 CHECK (reorder_level >= 0),
    warehouse_bin varchar(20) NOT NULL UNIQUE,
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE bookstore.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    full_name varchar(160) NOT NULL,
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    marketing_opt_in boolean NOT NULL DEFAULT false
);

CREATE TABLE bookstore.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES bookstore.customers(id) ON DELETE RESTRICT,
    status varchar(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'paid', 'packed', 'shipped', 'cancelled')),
    ordered_at timestamp with time zone NOT NULL DEFAULT now(),
    shipped_at timestamp with time zone,
    CHECK (shipped_at IS NULL OR shipped_at >= ordered_at)
);

CREATE TABLE bookstore.order_items (
    order_id bigint NOT NULL REFERENCES bookstore.orders(id) ON DELETE CASCADE,
    book_id bigint NOT NULL REFERENCES bookstore.books(id) ON DELETE RESTRICT,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(10,2) NOT NULL CHECK (unit_price >= 0),
    line_total numeric(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    PRIMARY KEY (order_id, book_id)
);

CREATE TABLE bookstore.reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL REFERENCES bookstore.books(id) ON DELETE CASCADE,
    customer_id bigint NOT NULL REFERENCES bookstore.customers(id) ON DELETE CASCADE,
    rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (book_id, customer_id)
);

CREATE INDEX books_title_idx ON bookstore.books (title);
CREATE INDEX orders_customer_ordered_idx ON bookstore.orders (customer_id, ordered_at DESC);
CREATE INDEX reviews_book_rating_idx ON bookstore.reviews (book_id, rating DESC);
CREATE INDEX books_metadata_idx ON bookstore.books USING gin (metadata);

CREATE FUNCTION bookstore.touch_inventory_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END
$$;

CREATE TRIGGER inventory_touch_updated_at
BEFORE UPDATE ON bookstore.inventory
FOR EACH ROW EXECUTE FUNCTION bookstore.touch_inventory_updated_at();

CREATE FUNCTION bookstore.order_total(target_order_id bigint) RETURNS numeric
LANGUAGE sql STABLE AS $$
    SELECT COALESCE(sum(line_total), 0)::numeric
    FROM bookstore.order_items
    WHERE order_id = target_order_id
$$;

INSERT INTO bookstore.publishers (id, name, country_code, founded_year) VALUES
    (1, 'Northstar Press', 'US', 1988),
    (2, 'Harbor House', 'GB', 1974),
    (3, 'Maple Leaf Books', 'CA', 2003),
    (4, 'Cedar & Ink', 'US', 1996),
    (5, 'Atlas Lantern', 'AU', 1981),
    (6, 'Juniper Editions', 'IE', 2008),
    (7, 'Redwood Academic', 'US', 1967),
    (8, 'Blue Heron Books', 'NZ', 1992),
    (9, 'Copperline Press', 'ZA', 2001),
    (10, 'Moonrise Media', 'JP', 2012);

INSERT INTO bookstore.authors (id, name, email, country_code, biography) VALUES
    (1, 'Maya Chen', 'maya@example.test', 'CA', 'Writes practical guides to data systems.'),
    (2, 'Jon Bell', 'jon@example.test', 'GB', 'Historian and essayist.'),
    (3, 'Amara Okafor', 'amara@example.test', 'NG', 'Novelist focused on cities and community.'),
    (4, 'Luis Ortega', 'luis@example.test', 'MX', 'Chef and food photographer.'),
    (5, 'Priya Raman', 'priya@example.test', 'IN', 'Software architect and educator.');

INSERT INTO bookstore.authors (id, name, email, country_code, biography)
SELECT author_number,
       (ARRAY['Avery','Cameron','Dara','Emery','Farah','Gideon','Hana','Inez','Jules','Kai','Leila','Micah'])[1 + ((author_number - 6) % 12)]
       || ' ' ||
       (ARRAY['Adler','Bennett','Costa','Dubois','El-Sayed','Fischer','Gupta','Hughes','Ito','Johnson','Kowalski','Laurent'])[1 + (((author_number - 6) / 12) % 12)],
       format('author%s@example.test', lpad(author_number::text, 2, '0')),
       (ARRAY['US','CA','GB','AU','IN','DE','FR','BR','JP','NG'])[1 + ((author_number - 1) % 10)],
       (ARRAY[
           'Explores how technology changes everyday work.',
           'Writes character-driven fiction about families and place.',
           'Researches history, trade, and material culture.',
           'Creates practical guides for curious lifelong learners.',
           'Combines field reporting with environmental science.'
       ])[1 + ((author_number - 1) % 5)]
FROM generate_series(6, 40) AS generated(author_number);

INSERT INTO bookstore.books (id, publisher_id, isbn, title, published_on, price, format, metadata) VALUES
    (1, 1, '9780000000001', 'Practical PostgreSQL Patterns', '2025-02-11', 44.00, 'paperback', '{"topics":["postgresql","design"],"level":"intermediate"}'),
    (2, 1, '9780000000002', 'Reliable Data Systems', '2024-09-03', 58.50, 'hardcover', '{"topics":["databases","operations"]}'),
    (3, 2, '9780000000003', 'A Short History of Maps', '2021-05-18', 28.00, 'paperback', '{"topics":["history","cartography"]}'),
    (4, 3, '9780000000004', 'The City Between Rivers', '2023-10-24', 19.95, 'paperback', '{"topics":["fiction"]}'),
    (5, 3, '9780000000005', 'Weeknight Kitchens', '2025-04-08', 34.00, 'hardcover', '{"topics":["cooking"]}'),
    (6, 1, '9780000000006', 'Schema Design Workbook', '2026-01-20', 24.00, 'ebook', '{"topics":["postgresql","education"]}');

INSERT INTO bookstore.books (id, publisher_id, isbn, title, published_on, price, format, metadata)
SELECT book_number,
       1 + ((book_number * 7) % 10),
       '978' || lpad(book_number::text, 10, '0'),
       (ARRAY['Hidden','Practical','Electric','Quiet','Brave','Modern','Forgotten','Essential','Curious','Infinite'])[1 + ((book_number - 1) % 10)]
       || ' ' ||
       (ARRAY['Gardens','Algorithms','Coastlines','Archives','Kitchens','Networks','Journeys','Workshops'])[1 + (((book_number - 1) / 10) % 8)]
       || ' ' || book_number,
       date '2016-01-01' + ((book_number * 43) % 3600),
       (12 + ((book_number * 137) % 6200) / 100.0)::numeric(10,2),
       (ARRAY['hardcover','paperback','ebook'])[1 + ((book_number - 1) % 3)],
       jsonb_build_object(
           'topics', jsonb_build_array(
               (ARRAY['technology','history','fiction','cooking','science','business','travel','art'])[1 + ((book_number - 1) % 8)],
               (ARRAY['design','culture','leadership','nature','craft','society'])[1 + ((book_number - 1) % 6)]
           ),
           'level', (ARRAY['introductory','intermediate','advanced'])[1 + ((book_number - 1) % 3)],
           'pages', 120 + ((book_number * 17) % 480)
       )
FROM generate_series(7, 80) AS generated(book_number);

INSERT INTO bookstore.book_authors (book_id, author_id, author_order) VALUES
    (1, 1, 1), (1, 5, 2), (2, 5, 1), (3, 2, 1),
    (4, 3, 1), (5, 4, 1), (6, 1, 1);
INSERT INTO bookstore.book_authors (book_id, author_id, author_order)
SELECT book_number, 1 + ((book_number * 7) % 40), 1
FROM generate_series(7, 80) AS generated(book_number);
INSERT INTO bookstore.book_authors (book_id, author_id, author_order)
SELECT book_number, 1 + ((book_number * 7 + 11) % 40), 2
FROM generate_series(9, 80, 3) AS generated(book_number);

INSERT INTO bookstore.inventory (book_id, on_hand, reorder_level, warehouse_bin) VALUES
    (1, 18, 5, 'A-01'), (2, 7, 4, 'A-02'), (3, 12, 4, 'B-01'),
    (4, 23, 6, 'B-02'), (5, 4, 5, 'C-01'), (6, 999, 0, 'DIGITAL');
INSERT INTO bookstore.inventory (book_id, on_hand, reorder_level, warehouse_bin, updated_at)
SELECT book_number,
       (book_number * 19) % 85,
       3 + (book_number % 9),
       'W-' || lpad(book_number::text, 3, '0'),
       timestamp with time zone '2026-06-10 12:00:00+00' - (book_number * interval '3 hours')
FROM generate_series(7, 80) AS generated(book_number);

INSERT INTO bookstore.customers (id, email, full_name, joined_at, marketing_opt_in) VALUES
    (1, 'alex@example.test', 'Alex Morgan', '2025-10-04 14:30:00+00', true),
    (2, 'sam@example.test', 'Sam Rivera', '2025-11-12 09:15:00+00', false),
    (3, 'taylor@example.test', 'Taylor Kim', '2026-01-08 17:45:00+00', true),
    (4, 'jordan@example.test', 'Jordan Patel', '2026-02-19 12:00:00+00', false);
INSERT INTO bookstore.customers (id, email, full_name, joined_at, marketing_opt_in)
SELECT customer_number,
       format('reader%s@example.test', lpad(customer_number::text, 3, '0')),
       (ARRAY['Alex','Blair','Casey','Devon','Elliot','Frankie','Gray','Harper','Indigo','Jamie','Kendall','Logan','Morgan','Noel','Oakley'])[1 + ((customer_number - 1) % 15)]
       || ' ' ||
       (ARRAY['Brooks','Campbell','Diaz','Evans','Foster','Green','Hayes','Ivanov','Jones','Khan'])[1 + (((customer_number - 1) / 15) % 10)],
       timestamp with time zone '2024-01-01 09:00:00+00' + (customer_number * interval '2 days 7 hours'),
       customer_number % 3 <> 0
FROM generate_series(5, 150) AS generated(customer_number);

INSERT INTO bookstore.orders (id, customer_id, status, ordered_at, shipped_at) VALUES
    (1, 1, 'shipped', '2026-06-02 10:30:00+00', '2026-06-03 16:00:00+00'),
    (2, 2, 'paid', '2026-06-05 13:20:00+00', NULL),
    (3, 1, 'packed', '2026-06-07 08:45:00+00', NULL),
    (4, 3, 'pending', '2026-06-08 19:10:00+00', NULL);
WITH generated_orders AS (
    SELECT order_number,
           1 + ((order_number * 37) % 150) AS customer_id,
           (ARRAY['pending','paid','packed','shipped','cancelled'])[1 + ((order_number - 1) % 5)] AS status,
           timestamp with time zone '2025-06-01 08:00:00+00' + (order_number * interval '15 hours') AS ordered_at
    FROM generate_series(5, 500) AS generated(order_number)
)
INSERT INTO bookstore.orders (id, customer_id, status, ordered_at, shipped_at)
SELECT order_number, customer_id, status, ordered_at,
       CASE WHEN status = 'shipped' THEN ordered_at + ((1 + (order_number % 5)) * interval '1 day') END
FROM generated_orders;

INSERT INTO bookstore.order_items (order_id, book_id, quantity, unit_price) VALUES
    (1, 1, 1, 44.00), (1, 4, 2, 19.95), (2, 2, 1, 58.50),
    (3, 5, 1, 34.00), (3, 6, 1, 24.00), (4, 3, 1, 28.00), (4, 4, 1, 19.95);
INSERT INTO bookstore.order_items (order_id, book_id, quantity, unit_price)
SELECT order_number,
       book.id,
       1 + ((order_number + item_number) % 3),
       book.price
FROM generate_series(5, 500) AS generated(order_number)
CROSS JOIN LATERAL generate_series(1, 1 + (order_number % 4)) AS items(item_number)
JOIN bookstore.books AS book ON book.id = 1 + ((order_number * 7 + item_number * 13) % 80);

INSERT INTO bookstore.reviews (book_id, customer_id, rating, review_text, created_at) VALUES
    (1, 1, 5, 'Clear examples and useful tradeoffs.', '2026-06-06 09:00:00+00'),
    (4, 1, 4, 'Beautifully observed characters.', '2026-06-07 18:30:00+00'),
    (2, 2, 5, 'A practical reference for production work.', '2026-06-08 11:15:00+00'),
    (3, 3, 4, 'Concise and richly illustrated.', '2026-06-09 07:40:00+00');
INSERT INTO bookstore.reviews (book_id, customer_id, rating, review_text, created_at)
SELECT 1 + ((orders.id * 7 + 13) % 80),
       orders.customer_id,
       1 + ((orders.id * 11) % 5),
       (ARRAY[
           'Fast-paced and easy to recommend.',
           'Useful ideas with several memorable examples.',
           'A thoughtful read that rewards a second look.',
           'Strong opening chapters and a satisfying conclusion.',
           'Clear, approachable, and full of practical detail.',
           'An unexpected favorite from this year.'
       ])[1 + ((orders.id - 1) % 6)],
       orders.ordered_at + interval '12 days'
FROM bookstore.orders
WHERE orders.id BETWEEN 5 AND 500
  AND orders.status IN ('paid', 'packed', 'shipped')
ON CONFLICT (book_id, customer_id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('bookstore.publishers', 'id'), (SELECT max(id) FROM bookstore.publishers));
SELECT setval(pg_get_serial_sequence('bookstore.authors', 'id'), (SELECT max(id) FROM bookstore.authors));
SELECT setval(pg_get_serial_sequence('bookstore.books', 'id'), (SELECT max(id) FROM bookstore.books));
SELECT setval(pg_get_serial_sequence('bookstore.customers', 'id'), (SELECT max(id) FROM bookstore.customers));
SELECT setval(pg_get_serial_sequence('bookstore.orders', 'id'), (SELECT max(id) FROM bookstore.orders));
SELECT setval(pg_get_serial_sequence('bookstore.reviews', 'id'), (SELECT max(id) FROM bookstore.reviews));

CREATE VIEW bookstore.book_catalog AS
SELECT books.id, books.isbn, books.title, publishers.name AS publisher,
       books.price, books.format, inventory.on_hand,
       string_agg(authors.name, ', ' ORDER BY book_authors.author_order) AS authors
FROM bookstore.books
JOIN bookstore.publishers ON publishers.id = books.publisher_id
JOIN bookstore.inventory ON inventory.book_id = books.id
JOIN bookstore.book_authors ON book_authors.book_id = books.id
JOIN bookstore.authors ON authors.id = book_authors.author_id
GROUP BY books.id, publishers.name, inventory.on_hand;

CREATE VIEW bookstore.order_summary AS
SELECT orders.id AS order_id, orders.customer_id, customers.full_name AS customer_name,
       orders.status, orders.ordered_at, orders.shipped_at,
       orders.ordered_at::date AS order_date,
       COALESCE(sum(order_items.quantity), 0)::bigint AS item_count,
       COALESCE(sum(order_items.line_total), 0)::numeric(14,2) AS order_total
FROM bookstore.orders
JOIN bookstore.customers ON customers.id = orders.customer_id
LEFT JOIN bookstore.order_items ON order_items.order_id = orders.id
GROUP BY orders.id, customers.full_name;

CREATE VIEW bookstore.low_stock_books AS
SELECT books.id AS book_id, books.isbn, books.title,
       publishers.name AS publisher_name, inventory.on_hand,
       inventory.reorder_level,
       inventory.reorder_level - inventory.on_hand AS units_below_reorder
FROM bookstore.books
JOIN bookstore.publishers ON publishers.id = books.publisher_id
JOIN bookstore.inventory ON inventory.book_id = books.id
WHERE inventory.on_hand < inventory.reorder_level;

CREATE VIEW bookstore.customer_order_totals AS
SELECT customers.id AS customer_id, customers.full_name AS customer_name,
       customers.email,
       count(DISTINCT orders.id) FILTER (WHERE orders.status <> 'cancelled')::bigint AS order_count,
       COALESCE(sum(order_items.quantity) FILTER (WHERE orders.status <> 'cancelled'), 0)::bigint AS item_count,
       COALESCE(sum(order_items.line_total) FILTER (WHERE orders.status <> 'cancelled'), 0)::numeric(14,2) AS lifetime_value,
       max(orders.ordered_at) FILTER (WHERE orders.status <> 'cancelled') AS last_ordered_at
FROM bookstore.customers
LEFT JOIN bookstore.orders ON orders.customer_id = customers.id
LEFT JOIN bookstore.order_items ON order_items.order_id = orders.id
GROUP BY customers.id;

CREATE MATERIALIZED VIEW bookstore.monthly_sales AS
SELECT date_trunc('month', orders.ordered_at AT TIME ZONE 'UTC')::date AS sales_month,
       count(DISTINCT orders.id)::bigint AS order_count,
       COALESCE(sum(order_items.quantity), 0)::bigint AS item_count,
       COALESCE(sum(order_items.line_total), 0)::numeric(14,2) AS gross_sales
FROM bookstore.orders
JOIN bookstore.order_items ON order_items.order_id = orders.id
WHERE orders.status IN ('paid', 'packed', 'shipped')
GROUP BY date_trunc('month', orders.ordered_at AT TIME ZONE 'UTC')::date;
CREATE UNIQUE INDEX monthly_sales_sales_month_uidx ON bookstore.monthly_sales (sales_month);

\endif
COMMIT;

-- catalog_lab adds PostgreSQL features not represented by Mercury Books.
BEGIN;
SELECT pg_advisory_xact_lock(hashtext('schemii:test-seed:catalog-lab')::bigint);
SELECT to_regnamespace('catalog_lab') IS NULL AS install_catalog_lab \gset
\if :install_catalog_lab
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE SCHEMA catalog_lab;
COMMENT ON SCHEMA catalog_lab IS 'Schemii seeded PostgreSQL catalog coverage lab; fixture=v1';

CREATE TYPE catalog_lab.work_state AS ENUM ('new', 'ready', 'running', 'done', 'failed');
CREATE DOMAIN catalog_lab.positive_integer AS integer CHECK (VALUE > 0);

CREATE TABLE catalog_lab.accounts (
    tenant_id bigint NOT NULL,
    account_id bigint NOT NULL,
    display_name text NOT NULL,
    state catalog_lab.work_state NOT NULL DEFAULT 'new',
    credit_limit catalog_lab.positive_integer NOT NULL DEFAULT 1000,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, account_id),
    UNIQUE (tenant_id, display_name)
);

CREATE TABLE catalog_lab.jobs (
    tenant_id bigint NOT NULL,
    job_id bigint GENERATED BY DEFAULT AS IDENTITY,
    account_id bigint NOT NULL,
    title text NOT NULL,
    title_length integer GENERATED ALWAYS AS (char_length(title)) STORED,
    state catalog_lab.work_state NOT NULL DEFAULT 'new',
    priority catalog_lab.positive_integer NOT NULL DEFAULT 1,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    scheduled_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, job_id),
    CONSTRAINT jobs_account_fk
        FOREIGN KEY (tenant_id, account_id)
        REFERENCES catalog_lab.accounts (tenant_id, account_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CHECK (scheduled_at IS NULL OR state IN ('ready', 'running', 'done', 'failed'))
);

CREATE UNIQUE INDEX jobs_one_ready_per_account_idx
    ON catalog_lab.jobs (tenant_id, account_id)
    WHERE state = 'ready';
CREATE INDEX jobs_payload_idx ON catalog_lab.jobs USING gin (payload);

CREATE FUNCTION catalog_lab.touch_job_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END
$$;
CREATE TRIGGER jobs_touch_updated_at
BEFORE UPDATE ON catalog_lab.jobs
FOR EACH ROW EXECUTE FUNCTION catalog_lab.touch_job_updated_at();

CREATE TABLE catalog_lab.events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY,
    occurred_on date NOT NULL,
    tenant_id bigint NOT NULL,
    account_id bigint NOT NULL,
    event_name text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (event_id, occurred_on),
    FOREIGN KEY (tenant_id, account_id)
        REFERENCES catalog_lab.accounts (tenant_id, account_id)
        ON DELETE CASCADE
) PARTITION BY RANGE (occurred_on);

CREATE TABLE catalog_lab.events_historical
    PARTITION OF catalog_lab.events FOR VALUES FROM (MINVALUE) TO ('2026-01-01');
CREATE TABLE catalog_lab.events_2026
    PARTITION OF catalog_lab.events FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
CREATE TABLE catalog_lab.events_future
    PARTITION OF catalog_lab.events FOR VALUES FROM ('2027-01-01') TO (MAXVALUE);

CREATE TABLE catalog_lab.reservations (
    reservation_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    resource_id bigint NOT NULL,
    reserved_during tstzrange NOT NULL,
    purpose text NOT NULL,
    EXCLUDE USING gist (resource_id WITH =, reserved_during WITH &&)
);

INSERT INTO catalog_lab.accounts
    (tenant_id, account_id, display_name, state, credit_limit, active, created_at)
VALUES
    (1, 100, 'Northwind Studio', 'ready', 5000, true, '2025-10-01 09:00:00+00'),
    (1, 101, 'Harbor Analytics', 'new', 2500, true, '2025-11-12 10:30:00+00'),
    (1, 102, 'Maple Operations', 'running', 8000, true, '2025-12-02 14:00:00+00'),
    (2, 200, 'Atlas Research', 'done', 12000, true, '2025-09-18 08:15:00+00'),
    (2, 201, 'Juniper Archive', 'failed', 1500, false, '2025-08-07 16:45:00+00');

INSERT INTO catalog_lab.jobs
    (tenant_id, job_id, account_id, title, state, priority, payload, scheduled_at, updated_at)
VALUES
    (1, 1, 100, 'Refresh customer segments', 'ready', 4, '{"source":"warehouse","batch":42}', '2026-08-30 12:00:00+00', '2026-08-29 18:00:00+00'),
    (1, 2, 100, 'Rebuild search index', 'done', 2, '{"index":"books"}', '2026-08-28 09:00:00+00', '2026-08-28 09:12:00+00'),
    (1, 3, 101, 'Import partner feed', 'new', 3, '{"partner":"harbor"}', NULL, '2026-08-29 08:00:00+00'),
    (1, 4, 102, 'Compact event history', 'running', 5, '{"before":"2025-01-01"}', '2026-08-30 10:00:00+00', '2026-08-30 10:04:00+00'),
    (2, 5, 200, 'Generate quarterly report', 'done', 2, '{"quarter":"2026-Q2"}', '2026-07-01 08:00:00+00', '2026-07-01 08:08:00+00'),
    (2, 6, 201, 'Verify archive checksums', 'failed', 1, '{"bucket":"cold-storage"}', '2026-08-20 15:00:00+00', '2026-08-20 15:03:00+00');

INSERT INTO catalog_lab.events
    (occurred_on, tenant_id, account_id, event_name, payload)
VALUES
    ('2025-12-20', 1, 100, 'account.created', '{"actor":"system"}'),
    ('2026-01-03', 1, 100, 'job.queued', '{"jobId":1}'),
    ('2026-02-14', 1, 101, 'feed.connected', '{"provider":"harbor"}'),
    ('2026-03-22', 1, 102, 'job.started', '{"jobId":4}'),
    ('2026-04-10', 2, 200, 'report.generated', '{"quarter":"2026-Q1"}'),
    ('2026-06-30', 2, 200, 'report.generated', '{"quarter":"2026-Q2"}'),
    ('2026-08-20', 2, 201, 'job.failed', '{"jobId":6,"retryable":true}'),
    ('2027-01-05', 1, 100, 'retention.scheduled', '{"months":18}');

INSERT INTO catalog_lab.reservations (resource_id, reserved_during, purpose) VALUES
    (10, '[2026-09-01 09:00:00+00,2026-09-01 10:00:00+00)', 'Catalog verification'),
    (10, '[2026-09-01 10:30:00+00,2026-09-01 11:30:00+00)', 'Migration rehearsal'),
    (11, '[2026-09-01 09:30:00+00,2026-09-01 12:00:00+00)', 'Load testing');

SELECT setval(pg_get_serial_sequence('catalog_lab.jobs', 'job_id'), (SELECT max(job_id) FROM catalog_lab.jobs));

CREATE FUNCTION catalog_lab.account_job_count(target_tenant_id bigint, target_account_id bigint)
RETURNS bigint LANGUAGE sql STABLE AS $$
    SELECT count(*)
    FROM catalog_lab.jobs
    WHERE tenant_id = target_tenant_id AND account_id = target_account_id
$$;

CREATE PROCEDURE catalog_lab.remove_finished_jobs(older_than timestamp with time zone)
LANGUAGE sql AS $$
    DELETE FROM catalog_lab.jobs
    WHERE state IN ('done', 'failed') AND updated_at < older_than
$$;

CREATE VIEW catalog_lab.active_jobs AS
SELECT jobs.tenant_id, jobs.job_id, accounts.display_name AS account,
       jobs.title, jobs.state, jobs.priority, jobs.scheduled_at, jobs.updated_at
FROM catalog_lab.jobs
JOIN catalog_lab.accounts USING (tenant_id, account_id)
WHERE jobs.state IN ('ready', 'running');

CREATE VIEW catalog_lab.event_rollup AS
SELECT tenant_id, account_id, event_name, count(*)::bigint AS event_count,
       min(occurred_on) AS first_seen_on, max(occurred_on) AS last_seen_on
FROM catalog_lab.events
GROUP BY tenant_id, account_id, event_name;

CREATE MATERIALIZED VIEW catalog_lab.account_activity AS
SELECT accounts.tenant_id, accounts.account_id, accounts.display_name,
       (SELECT count(*) FROM catalog_lab.jobs
        WHERE jobs.tenant_id = accounts.tenant_id AND jobs.account_id = accounts.account_id)::bigint AS job_count,
       (SELECT count(*) FROM catalog_lab.events
        WHERE events.tenant_id = accounts.tenant_id AND events.account_id = accounts.account_id)::bigint AS event_count
FROM catalog_lab.accounts;
CREATE UNIQUE INDEX account_activity_identity_uidx
    ON catalog_lab.account_activity (tenant_id, account_id);

CREATE MATERIALIZED VIEW catalog_lab.queued_job_snapshot AS
SELECT tenant_id, job_id, account_id, title, priority, scheduled_at
FROM catalog_lab.jobs
WHERE state = 'ready'
WITH NO DATA;

\endif
COMMIT;

DO $verification$
BEGIN
    IF obj_description(to_regnamespace('bookstore'), 'pg_namespace')
       IS DISTINCT FROM 'Schemii seeded Mercury Books test dataset; fixture=v1' THEN
        RAISE EXCEPTION 'bookstore fixture is missing or outdated; recreate the Compose volume';
    END IF;
    IF obj_description(to_regnamespace('catalog_lab'), 'pg_namespace')
       IS DISTINCT FROM 'Schemii seeded PostgreSQL catalog coverage lab; fixture=v1' THEN
        RAISE EXCEPTION 'catalog_lab fixture is missing or outdated; recreate the Compose volume';
    END IF;
    IF (SELECT count(*) FROM bookstore.books) <> 80
       OR (SELECT count(*) FROM bookstore.customers) <> 150
       OR (SELECT count(*) FROM bookstore.orders) <> 500 THEN
        RAISE EXCEPTION 'Mercury Books seed row counts are incomplete';
    END IF;
    IF (SELECT count(*) FROM catalog_lab.accounts) <> 5
       OR (SELECT count(*) FROM catalog_lab.jobs) <> 6
       OR (SELECT count(*) FROM catalog_lab.events) <> 8 THEN
        RAISE EXCEPTION 'catalog_lab seed row counts are incomplete';
    END IF;
END
$verification$;

SELECT 'bookstore' AS namespace, 9 AS base_tables, 500 AS orders
UNION ALL
SELECT 'catalog_lab', 7, 6;
