import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { request } from "@playwright/test";
import { ensureDatabaseFixtures } from "./helpers/database-fixtures.js";

export default async function globalSetup(config) {
  if (process.env.SCHEMII_E2E_BOOTSTRAP !== "1") return;
  const context = await request.newContext({
    baseURL: config.projects[0].use.baseURL,
    ignoreHTTPSErrors: true,
  });
  try {
    await ensureDatabaseFixtures(context, {
      username: process.env.SCHEMII_TEST_POSTGRES_USER || "schemii",
      password: async () => {
        if (process.env.SCHEMII_TEST_POSTGRES_PASSWORD) return process.env.SCHEMII_TEST_POSTGRES_PASSWORD;
        const directory = process.env.SCHEMII_SECRET_DIRECTORY || resolve(".schemii/secrets");
        const password = (await readFile(resolve(directory, "demo_target_password"), "utf8")).split("\n", 1)[0];
        if (!password) throw new Error("Browser fixtures require the demo target secret generated by ./start.sh");
        return password;
      },
    });
  } finally {
    await context.dispose();
  }
}
