import { chmod, mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { randomBytes } from "node:crypto";
import { accountCredentials } from "./helpers/account-auth.js";
import { request } from "@playwright/test";
import { ensureDatabaseFixtures } from "./helpers/database-fixtures.js";

export default async function globalSetup(config) {
  const statePath = resolve(config.projects[0].use.storageState);
  await mkdir(dirname(statePath), { recursive: true, mode: 0o700 });
  await chmod(dirname(statePath), 0o700);
  await unlink(statePath).catch(error => { if (error.code !== 'ENOENT') throw error; });
  const context = await request.newContext({
    baseURL: config.projects[0].use.baseURL,
    ignoreHTTPSErrors: true,
    extraHTTPHeaders: { Origin: new URL(config.projects[0].use.baseURL).origin },
  });
  try {
    const statusResponse = await context.get('/api/v1/auth/status');
    if (!statusResponse.ok()) throw new Error(`Cannot check browser account authentication (HTTP ${statusResponse.status()}).`);
    const status = await statusResponse.json();
    if (status.enabled) {
      const credentials = await accountCredentials();
      let response;
      if (status.setup_required) {
        if (process.env.SCHEMII_E2E_BOOTSTRAP !== '1') throw new Error('First account setup requires explicit SCHEMII_E2E_BOOTSTRAP=1.');
        const directory = process.env.SCHEMII_SECRET_DIRECTORY || resolve('.schemii/secrets');
        const setupToken = (await readFile(resolve(directory, 'account_setup_token'), 'utf8')).trim();
        if (!setupToken) throw new Error('Browser setup requires the account setup token generated by ./start.sh.');
        response = await context.post('/api/v1/auth/setup', { data: {
          setup_token: setupToken,
          username: credentials?.username || `e2e_admin_${randomBytes(6).toString('hex')}`,
          display_name: 'Browser test administrator',
          password: credentials?.password || randomBytes(32).toString('base64url'),
        } });
      } else {
        if (!credentials) throw new Error('This installation already has accounts. Set SCHEMII_E2E_USERNAME and SCHEMII_E2E_PASSWORD, or explicitly opt in with SCHEMII_E2E_CREDENTIALS_FILE.');
        response = await context.post('/api/v1/auth/login', { data: credentials });
      }
      if (!response.ok()) throw new Error(`Browser account authentication failed (HTTP ${response.status()}).`);
      const identity = await response.json();
      if (!identity.is_admin) throw new Error('Browser fixtures require an administrator test account.');
    }
    // Write with private permissions from creation; never print credentials or cookie state.
    await writeFile(statePath, JSON.stringify(await context.storageState()), { mode: 0o600 });
    await chmod(statePath, 0o600);
    if (process.env.SCHEMII_E2E_BOOTSTRAP !== "1") return;
    await ensureDatabaseFixtures(context, {
      username: process.env.SCHEMII_TEST_POSTGRES_USER || "schemii",
      password: async () => {
        if (process.env.SCHEMII_TEST_POSTGRES_PASSWORD) return process.env.SCHEMII_TEST_POSTGRES_PASSWORD;
        const directory = process.env.SCHEMII_SECRET_DIRECTORY || resolve(".schemii/secrets");
        const password = (await readFile(resolve(directory, "demo_target_password"), "utf8")).split("\n", 1)[0];
        if (!password) throw new Error("Browser fixtures require the demo target secret generated by ./start.sh");
        return password;
      },
    });
  } finally {
    await context.dispose();
  }
}
