import { chmod, mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { accountStorageState, authenticateBrowserAccount } from "./helpers/account-auth.js";
import { readParallelAccounts, verifyParallelAccount, writeParallelStorageState } from "./helpers/parallel-account.js";
import { ensureDatabaseFixtures } from "./helpers/database-fixtures.js";

export default async function globalSetup(config, { environment = process.env, requestFactory } = {}) {
  requestFactory ||= (await import('@playwright/test')).request;
  const statePath = resolve(config.projects[0].use.storageState);
  const parallel = environment.SCHEMII_E2E_PARALLEL_ACCOUNTS_FILE || environment.SCHEMII_E2E_PROCESS_INDEX;
  let selected;
  if (parallel) {
    if (statePath !== accountStorageState(environment)) throw new Error('Parallel browser config must select its process-owned authentication state.');
    const manifest = await readParallelAccounts(environment.SCHEMII_E2E_PARALLEL_ACCOUNTS_FILE);
    if (manifest.baseURL !== config.projects[0].use.baseURL) throw new Error('Parallel browser manifest origin differs from the configured application.');
    if (environment.SCHEMII_E2E_SOURCE_ROOT !== manifest.sourceRoot) throw new Error('Parallel browser source root differs from its prepared manifest.');
    selected = manifest.accounts[Number(environment.SCHEMII_E2E_PROCESS_INDEX) - 1];
  }
  await mkdir(dirname(statePath), { recursive: true, mode: 0o700 });
  await chmod(dirname(statePath), 0o700);
  if (!selected) await unlink(statePath).catch(error => { if (error.code !== 'ENOENT') throw error; });
  const context = await requestFactory.newContext({
    baseURL: config.projects[0].use.baseURL,
    ignoreHTTPSErrors: true,
    extraHTTPHeaders: { Origin: new URL(config.projects[0].use.baseURL).origin },
  });
  try {
    const { identity } = await authenticateBrowserAccount(context, environment);
    if (selected) await verifyParallelAccount(context, selected, identity);
    // Write with private permissions from creation; never print credentials or cookie state.
    if (selected) await writeParallelStorageState(selected, await context.storageState());
    else {
      await writeFile(statePath, JSON.stringify(await context.storageState()), { mode: 0o600 });
      await chmod(statePath, 0o600);
    }
    if (selected || environment.SCHEMII_E2E_BOOTSTRAP !== "1") return;
    await ensureDatabaseFixtures(context, {
      username: environment.SCHEMII_TEST_POSTGRES_USER || "schemii",
      password: async () => {
        if (environment.SCHEMII_TEST_POSTGRES_PASSWORD) return environment.SCHEMII_TEST_POSTGRES_PASSWORD;
        const directory = environment.SCHEMII_SECRET_DIRECTORY || resolve(".schemii/secrets");
        const password = (await readFile(resolve(directory, "demo_target_password"), "utf8")).split("\n", 1)[0];
        if (!password) throw new Error("Browser fixtures require the demo target secret generated by ./start.sh");
        return password;
      },
    });
  } finally {
    await context.dispose();
  }
}
