import { expect, test } from "@playwright/test";
import { chooseModelOption, expectDropdownWithinViewport } from "./helpers/schemoo-select.js";
import { findOrganizationConnection } from "./helpers/schemoo-model.js";
import { importedDraft } from "../../src/schemii/schemoo/web/model-draft.js";
import { splitDraft } from "../../src/schemii/schemoo/web/model-state.js";

let modelId;
test.beforeEach(async ({ request }) => {
  const connection = findOrganizationConnection((await (await request.get("/api/v1/connections")).json()).connections);
  expect(connection).toBeTruthy();
  const catalog = await (await request.get(`/api/v1/schemoo/catalog?connection_id=${connection.id}&namespace=public`)).json();
  const draft = importedDraft(catalog);
  draft.edges.forEach(e => { e.enabled = false; });
  draft.root = "personnel_dim"; draft.fields = [{ table: "personnel_dim", column: "name" }]; draft.scopes = [];
  const created = await request.post("/api/v1/schemoo/models", { data: { name: `E2E filter dialog ${Date.now()}`, connectionId: connection.id, namespace: "public", catalogFingerprint: catalog.fingerprint, ...splitDraft(draft) } });
  expect(created.ok(), await created.text()).toBeTruthy(); modelId = (await created.json()).id;
});
test.afterEach(async ({ request }) => {
  if (!modelId) return;
  const response = await request.get(`/api/v1/schemoo/models/${modelId}`);
  if (response.ok()) await request.delete(`/api/v1/schemoo/models/${modelId}?expected_revision=${(await response.json()).revision}`);
  modelId = null;
});

test("fixed domain selection works before save and remains a literal after reload", async ({ page, request }) => {
  await page.goto(`/schemoo?model=${modelId}`);
  await page.getByRole("button", { name: "Model filters", exact: true }).click();
  await page.getByRole("button", { name: "Add model filter scope", exact: true }).click();
  await page.getByRole("button", { name: /^Fixed rule/ }).click();
  await chooseModelOption(page, "Model filter / Default condition 1 field", "personnel_dim · id");
  await chooseModelOption(page, "Model filter / Default condition 1 operator", "Equals");
  await page.getByRole("checkbox", { name: "Model filter / Default condition 1 choose fixed value from domain", exact: true }).check();
  await page.getByRole("button", { name: "Apply to model", exact: true }).click();
  await expect(page.locator(".mf-dialog-error")).toHaveText("Choose a fixed value from the domain list.");
  const browse = page.getByRole("combobox", { name: "Model filter / Default condition 1 value", exact: true });
  await browse.click();
  const options = page.locator(".ui-async-value-select__list:visible [role=option]");
  await expect(options.first()).toBeVisible({ timeout: 30000 });
  await browse.press("Escape");
  await expect(page.locator(".mf-dialog")).toBeVisible();
  await browse.click();
  await expect(options.first()).toBeVisible({ timeout: 30000 });
  const selected = await options.first().locator("strong").innerText();
  await browse.fill(selected);
  await expect(options).toHaveCount(1, { timeout: 30000 });
  await page.screenshot({ path: `artifacts/fixed-domain-picker-${test.info().project.name}.png` });
  await options.first().click();
  await expect(browse).toHaveValue(selected);
  await expect(page.locator(".mf-dialog-summary")).toContainText(selected);
  const savedBefore = await (await request.get(`/api/v1/schemoo/models/${modelId}`)).json();
  expect(savedBefore.definition.scopes).toEqual([]);
  await page.screenshot({ path: `artifacts/fixed-domain-rule-${test.info().project.name}.png` });
  await page.getByRole("button", { name: "Apply to model", exact: true }).click();
  await page.getByRole("button", { name: "Save model", exact: true }).click();
  await expect(page.locator("#draft-status")).toContainText("Saved");
  await page.reload();
  await page.getByRole("button", { name: "Explore model", exact: true }).click();
  await expect(page.locator("#parameter-values input")).toHaveCount(0);
  await expect(page.locator("#sql")).toContainText(selected);
  await page.getByRole("button", { name: "Run preview", exact: true }).click();
  await expect(page.locator("#results table tbody tr")).toHaveCount(1);
});

test("alias roles are selectable for domain values and source bindings and survive reload", async ({ page }) => {
  await page.goto(`/schemoo?model=${modelId}`);
  await expect(page.locator('[data-node-id="personnel_dim"] .sc-node-header')).toBeVisible();
  if (await page.locator("#inspector").isVisible()) await page.getByRole("button", { name: "Close inspector", exact: true }).click();
  await page.locator('[data-node-id="personnel_dim"] .sc-node-header').click();
  await page.getByRole("button", { name: "Create alias", exact: true }).click();
  await page.getByRole("textbox", { name: "Alias name for personnel_dim", exact: true }).fill("Domain people");
  await page.getByRole("button", { name: "Add alias to model", exact: true }).click();
  await page.getByRole("button", { name: "Model filters", exact: true }).click();
  await page.getByRole("button", { name: "Add model filter scope", exact: true }).click();
  await page.getByRole("button", { name: /^Report parameter/ }).click();
  await chooseModelOption(page, "Evaluation reach for Model filter", "When its source participates");
  await chooseModelOption(page, "Model filter / Default condition 1 field", "Domain people · id");
  await page.getByRole("checkbox", { name: "Use searchable domain values for Parameter", exact: true }).check();
  const domain = page.getByRole("combobox", { name: /input .+ domain value column$/ });
  await expect(domain).toHaveValue("Domain people · id");
  await domain.fill("Domain people");
  await expectDropdownWithinViewport(domain);
  await page.screenshot({ path: `artifacts/alias-domain-${test.info().project.name}.png` });
  await page.getByRole("option", { name: "Domain people · id", exact: true }).click();
  await chooseModelOption(page, /input .+ domain label column$/, "name");
  await page.getByRole("button", { name: "Apply to model", exact: true }).click();
  await page.getByRole("button", { name: "Save model", exact: true }).click();
  await expect(page.locator("#draft-status")).toContainText("Saved");
  await page.reload();
  await page.getByRole("button", { name: "Model filters", exact: true }).click();
  await page.getByRole("button", { name: "Edit filter Model filter", exact: true }).click();
  await expect(page.getByRole("combobox", { name: /input .+ domain value column$/ })).toHaveValue("Domain people · id");
  await expect(page.getByRole("combobox", { name: "Model filter / Default condition 1 field", exact: true })).toHaveValue("Domain people · id");
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await page.getByRole("button", { name: "Explore model", exact: true }).click();
  await page.getByRole("combobox", { name: "Model filter: Parameter", exact: true }).click();
  const options = page.locator(".ui-async-value-select__list:visible [role=option]");
  await expect(options.first()).toBeVisible({ timeout: 30000 });
  await options.first().click();
  await expect(page.getByRole("combobox", { name: "Model filter: Parameter", exact: true })).not.toHaveValue("");
});

test("fixed filter dialog: searchable bindings, validation, cancel, save and preview", async ({ page }) => {
  const errors = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto(`/schemoo?model=${modelId}`);
  await page.getByRole("button", { name: "Model filters", exact: true }).click();
  await page.getByRole("button", { name: "Add model filter scope", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Add model filter", exact: true });
  await expect(dialog).toBeVisible();
  await page.screenshot({ path: `artifacts/filter-choice-${test.info().project.name}.png` });
  await page.getByRole("button", { name: /^Fixed rule/ }).click();
  await page.getByRole("button", { name: "Apply to model", exact: true }).click();
  await expect(dialog.getByRole("alert")).toContainText("Choose a valid source column");
  const source = page.getByRole("combobox", { name: "Model filter / Default condition 1 field", exact: true });
  await source.fill("personnel_dim · name");
  await expect(page.getByRole("option", { name: "personnel_dim · name", exact: true })).toBeVisible();
  await expectDropdownWithinViewport(source);
  await page.screenshot({ path: `artifacts/filter-dropdown-${test.info().project.name}.png` });
  await page.getByRole("option", { name: "personnel_dim · name", exact: true }).click();
  await page.getByRole("textbox", { name: /^Scope .+ name$/ }).fill("Named personnel");
  await expect(dialog.getByRole("complementary", { name: "Filter summary" })).toContainText("personnel_dim.name is not null");
  await expect(dialog.getByRole("textbox", { name: /condition 1 value$/ })).toHaveCount(0);
  await page.screenshot({ path: `artifacts/filter-fixed-${test.info().project.name}.png` });
  await page.getByRole("button", { name: "Apply to model", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.locator("#sql")).toContainText("IS NOT NULL");
  await page.getByRole("button", { name: "Edit filter Named personnel", exact: true }).click();
  await page.getByRole("textbox", { name: /^Scope .+ name$/ }).fill("Discard me");
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByRole("button", { name: "Edit filter Named personnel", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Add model filter scope", exact: true }).click();
  await page.getByRole("button", { name: /^Fixed rule/ }).click();
  await page.keyboard.press("Escape");
  await expect(page.locator(".mf-filter-card")).toHaveCount(1);
  await page.getByRole("button", { name: "Save model", exact: true }).click();
  await expect(page.locator("#draft-status")).toContainText("Saved");
  await page.reload();
  await page.getByRole("button", { name: "Explore model", exact: true }).click();
  await expect(page.locator("#parameter-values")).toContainText("Fixed model rule · no input required");
  await expect(page.locator("#parameter-values input")).toHaveCount(0);
  await page.getByRole("button", { name: "Run preview", exact: true }).click();
  await expect(page.locator("#results table")).toBeVisible();
  expect(errors).toEqual([]);
});

test("relative date defaults persist and compile to dates", async ({ page, request }, testInfo) => {
  await page.goto(`/schemoo?model=${modelId}`);
  await page.getByRole("button", { name: "Model filters", exact: true }).click();
  await page.getByRole("button", { name: "Add model filter scope", exact: true }).click();
  await page.getByRole("button", { name: /^Report parameter/ }).click();
  await chooseModelOption(page, "Model filter / Default condition 1 field", "personnel_dim · name");
  const type = page.getByRole("combobox", { name: /^Model filter \/ Default input .+ type$/ });
  await chooseModelOption(page, await type.getAttribute("aria-label"), "Date");
  const value = page.getByRole("textbox", { name: /^Model filter \/ Default input .+ default$/ });
  await expect(value).toHaveAttribute("placeholder", /today - 365/);
  await value.fill("today - 365");
  await value.scrollIntoViewIfNeeded();
  await page.screenshot({ path: `artifacts/relative-date-${testInfo.project.name}.png` });
  await page.getByRole("button", { name: "Apply to model", exact: true }).click();
  const expected = new Date(); expected.setUTCDate(expected.getUTCDate() - 365);
  await expect(page.locator("#sql")).toContainText(expected.toISOString().slice(0, 10));
  await page.getByRole("button", { name: "Save model", exact: true }).click();
  await expect(page.locator("#draft-status")).toContainText("Saved");
  const saved = await (await request.get(`/api/v1/schemoo/models/${modelId}`)).json();
  expect(saved.definition.scopes[0].alternatives[0].inputs[0].defaultValue).toBe("today - 365");
});

test("report parameter dialog binds inputs and changing to a null rule clears nullable state", async ({ page }) => {
  await page.goto(`/schemoo?model=${modelId}`);
  await page.getByRole("button", { name: "Model filters", exact: true }).click();
  await page.getByRole("button", { name: "Add model filter scope", exact: true }).click();
  await page.getByRole("button", { name: /^Report parameter/ }).click();
  await chooseModelOption(page, "Model filter / Default condition 1 field", "personnel_dim · name");
  await page.getByRole("textbox", { name: /^Model filter \/ Default input .+ default$/ }).fill("Example");
  await page.getByRole("checkbox", { name: "Model filter / Default condition 1 also accepts null", exact: true }).check();
  await page.screenshot({ path: `artifacts/filter-parameter-${test.info().project.name}.png` });
  await page.getByRole("button", { name: "Apply to model", exact: true }).click();
  await expect(page.locator("#sql")).toContainText("Example");
  await expect(page.locator("#sql")).toContainText("IS NULL");
  await page.getByRole("button", { name: "Edit filter Model filter", exact: true }).click();
  await chooseModelOption(page, "Model filter / Default condition 1 operator", "Is not null");
  await page.getByRole("button", { name: "Apply to model", exact: true }).click();
  await expect(page.locator(".mf-dialog-error")).toContainText("unused input");
  await page.getByRole("button", { name: "Delete input Parameter", exact: true }).click();
  await page.getByRole("button", { name: "Apply to model", exact: true }).click();
  await expect(page.locator("#sql")).toContainText("IS NOT NULL");
  await expect(page.locator("#sql")).not.toContainText("OR");
});

test("filter evaluation reach and unmatched-row policy are independent and persist", async ({ page, request }) => {
  await page.goto(`/schemoo?model=${modelId}`);
  await page.getByRole("button", { name: "Model filters", exact: true }).click();
  await page.getByRole("button", { name: "Add model filter scope", exact: true }).click();
  await page.getByRole("button", { name: /^Fixed rule/ }).click();
  await chooseModelOption(page, "Model filter / Default condition 1 field", "personnel_dim · id");
  await chooseModelOption(page, "Model filter / Default condition 1 operator", "Is not null");
  await chooseModelOption(page, "Matching rows for Model filter", "Keep unmatched parent rows");
  await chooseModelOption(page, "Evaluation reach for Model filter", "When its source participates");
  await expect(page.getByRole("combobox", { name: "Matching rows for Model filter", exact: true })).toHaveValue("Keep unmatched parent rows");
  await chooseModelOption(page, "Matching rows for Model filter", "Require matching rows");
  await expect(page.getByRole("combobox", { name: "Evaluation reach for Model filter", exact: true })).toHaveValue("When its source participates");
  await page.getByRole("button", { name: "Apply to model", exact: true }).click();
  await page.getByRole("button", { name: "Save model", exact: true }).click();
  await expect(page.locator("#draft-status")).toContainText("Saved");
  const saved = await (await request.get(`/api/v1/schemoo/models/${modelId}`)).json();
  expect(saved.definition.scopes[0]).toMatchObject({kind: "conditional", requirement: "required", rowBehavior: "require_matching"});
  await page.reload();
  await page.getByRole("button", { name: "Model filters", exact: true }).click();
  await expect(page.locator("#model-filters")).toContainText("Require matching rows");
});
