const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("src/schemii/schemer_web/index.html", "utf8");
const source = fs.readFileSync("src/schemii/schemer_web/app.js", "utf8");
const shared = fs.readFileSync("src/schemii/shared_web/ai-assistant.js", "utf8");
const styles = fs.readFileSync("src/schemii/shared_web/ai-assistant.css", "utf8");

assert.match(html, /id="ai-button"[\s\S]*class="ai-panel"[\s\S]*data-ai="model"[\s\S]*data-ai="access"[\s\S]*data-ai="messages"[\s\S]*data-ai="prompt"/, "Schemer needs the canonical shared model, disclosure, chat, and composer UI");
assert.match(html, /id="ai-settings-dialog"[\s\S]*separate from provider credentials[\s\S]*id="ai-history-dialog"[\s\S]*Schemii conversations remain separate/, "Schemer must separate policy/provider settings and app-specific chat history");
assert.match(shared, /Provider connections are shared by Schemii and Schemer/, "the shared settings component must explain cross-product provider credentials");
assert.match(html, /\/shared\/ai-assistant\.css[\s\S]*\/shared\/ai-assistant\.js/, "Schemer must load the shared AI client and visual shell");
assert.match(shared, /path\.startsWith\("\/api\/ai\/"\)/, "AI traffic must stay on Schemer's same-origin API");
assert.doesNotMatch(shared, /fetch\([^)]*(?:opencode|8080|provider\.)/i, "the browser must not call Schemii, OpenCode, or providers directly");
assert.match(shared, /localStorage\.setItem\(storageKey, normalized\)/, "browser storage may remember only a validated provider/model preference");
assert.equal((shared.match(/localStorage\.setItem\(/g) || []).length, 1, "provider credentials must never enter browser storage");
for (const safeAssignment of [/body\.textContent = value/, /body\.textContent = part\.text/, /summary\.textContent = normalized\.summary/]) assert.match(shared, safeAssignment, "untrusted model content and proposals must render through textContent");
assert.doesNotMatch(shared, /innerHTML|eval\(|new Function/, "the AI renderer must not interpret model output as code or HTML");
assert.match(shared, /\/activity`[\s\S]*getReader\(\)/, "Schemer AI needs bounded same-origin live activity");
assert.match(shared, /event\.type === "part"/, "Schemer AI must render bounded activity parts");
for (const route of ["/api/ai/auth/api", "/api/ai/auth/oauth/authorize", "/api/ai/auth/oauth/callback"]) assert.ok(shared.includes(route), `${route} must be handled by the shared provider UI`);
assert.match(shared, /Disconnect .*This affects both Schemii and Schemer/, "shared provider disconnect must explain its cross-app effect");
assert.match(shared, /\/api\/ai\/sessions[\s\S]*renderHistory[\s\S]*session\.id[\s\S]*method: "DELETE"/, "Schemer needs persistent app-isolated chat history");
assert.match(source, /buildSessionPayload:[\s\S]*dashboardId: context\.dashboardId, accessLevel[\s\S]*profileId: context\.profileId, database: context\.database, namespace: context\.namespace/, "Schemer must send the complete initial chat context for server-owned binding");
const aiAdapter = source.slice(source.indexOf("function schemerAiTarget"), source.indexOf('document.querySelector("#connections-button")'));
assert.doesNotMatch(aiAdapter, /SCHEMER_CONTEXT|aiContextFingerprint|profileFingerprint/, "Schemer AI authority must not use titles or browser-derived connection fingerprints");
assert.match(source, /parseSession: session =>[\s\S]*session\.target[\s\S]*session\.dashboardId[\s\S]*session\.accessLevel/, "Schemer must parse server-owned chat fields");
assert.match(shared, /binding\.key == null \|\| binding\.key === currentKey[\s\S]*state\.sessionId = resumable \? session\.id : null/, "history may continue only in its original dashboard and disclosure context");
assert.match(source, /function validateSchemerAiAction[\s\S]*exactFields[\s\S]*expectedRevision[\s\S]*currentTitle/, "Schemer actions must use strict fields, revisions, and exact widget identity");
assert.match(source, /action\.dashboardId !== capture\.dashboardId \|\| action\.expectedRevision !== capture\.revision/, "local dashboard revisions must invalidate stale proposal cards");
assert.doesNotMatch(source, /applyAction: applySchemerAiAction/, "Schemer proposals must not execute browser-owned dashboard mutations");
assert.match(shared, /proposalRequest\(proposal, "execute", body\)[\s\S]*proposalRequest\(proposal, "reconcile", context\)/, "Schemer must use idempotent server execute and reconcile operations");
assert.match(source, /buildProposalExecutionPayload: \(\{ confirmation \}\) => \(\{ confirmation \}\)/, "Schemer proposal execution may send only explicit confirmation");
const messageAdapter = source.slice(source.indexOf("buildMessagePayload:"), source.indexOf("buildHistoryQuery:"));
assert.doesNotMatch(messageAdapter, /password|connectionString|host|\buser\b|profileFingerprint/i, "Schemer AI messages must not expose connection credentials or local identity fingerprints");
assert.match(html, /value="data"[\s\S]*data-ai-query-warning/, "Schemer must expose an explicit data tier with a query safety warning");
assert.doesNotMatch(html, /allow-session/, "Schemer must require confirmation for every analytic query");
assert.match(source, /action\.type === "read_query"[\s\S]*action\.readOnly !== true[\s\S]*expectedRevision[\s\S]*buttonLabel: "Review & run query"/, "query proposals must be strict, read-only, revision-bound, and inert");
assert.match(shared, /confirm\(`\$\{normalized\.summary\}\$\{consequence\}\\n\\nConfirm this reviewed action\?`\)/, "every Schemer operation must require one post-review confirmation with destructive wording when needed");
assert.match(shared, /function beginProposalOperation[\s\S]*button\.textContent = "Running\.\.\."[\s\S]*const activity = beginProposalOperation\(card,[\s\S]*activity\.finish\("completed"\)[\s\S]*activity\.finish\(cancelled \? "cancelled" : operationSucceeded \? "warning" : "failed"\)/, "Schemer proposals must show live and authoritative terminal operation timing through the shared renderer");
assert.match(shared, /normalized\.action\?\.type === "read_query"[\s\S]*onCancel: \(\) => cancelProposal\(proposal\)/, "Schemer analytic queries must expose the shared Stop action only while running");
assert.match(styles, /\.ai-action-progress\.cancelled[\s\S]*\.ai-action-cancel/, "Schemer query cancellation needs a distinct terminal state and Stop control");
assert.match(source, /function schemerAiTargetLabel[\s\S]*toolbarTargetExplicit \? "selected" : "suggested"/, "Schemer AI must name whether its exact toolbar target was selected or merely suggested");
assert.match(source, /result\?\.kind === "sql_result"[\s\S]*persistedAfter[\s\S]*appendQueryResult\(result\.display\)[\s\S]*resultRef: result\.resultRef/, "approved result references must retain local dashboard safety checks before follow-up delivery");
assert.doesNotMatch(source, /queryResult: boundedSchemerAiQueryResult\(result\)/, "browser-owned rows must not be submitted as AI query provenance");
assert.match(source, /canViewSession: \(binding, currentKey\) => binding\.accessLevel !== "data" \|\| binding\.key === currentKey/, "data history must remain hidden outside its exact target context");
assert.match(messageAdapter, /text, model,[\s\S]*resultRef/, "ordinary messages may carry only text, model, and an optional result reference");
assert.doesNotMatch(messageAdapter, /dashboardId|accessLevel|profileId|database|namespace|expectedRevision/, "message authority context must remain server-owned");
const boundStart = shared.indexOf("function boundedAiQueryResult");
const boundEnd = shared.indexOf("function createAiAssistant", boundStart);
const boundContext = require("node:vm").createContext({ TextEncoder });
require("node:vm").runInContext(`${shared.slice(boundStart, boundEnd)}\nthis.boundResult = boundedAiQueryResult;`, boundContext);
const oversizedRows = Array.from({ length: 100 }, () => ["x".repeat(2000)]);
const bounded = boundContext.boundResult({ columns: [{ name: "value" }], rows: oversizedRows, truncated: false }, { maxRows: 100, maxColumns: 50, maxBytes: 48 * 1024, envelope: { profileId: "shared", database: "demo", namespace: "public", maxRows: 100, maxColumns: 50, maxResultBytes: 256 * 1024 } });
assert.ok(new TextEncoder().encode(JSON.stringify(bounded)).length <= 48 * 1024, "model query results must obey the UTF-8 byte limit");
assert.equal(bounded.rowCount, bounded.rows.length, "bounded results must contain only whole rows");
assert.equal(bounded.truncated, true, "bounded results must disclose truncation");
assert.match(styles, /\.ai-panel \{[^}]*position: fixed;[^}]*left: 0;[^}]*translate3d\(-100%[\s\S]*\.ai-panel\.open[\s\S]*@media \(prefers-reduced-motion: reduce\)/, "the shared AI panel needs canonical left-drawer motion with a reduced-motion fallback");
assert.match(styles, /\.ai-action-progress\.completed[\s\S]*\.ai-action-progress\.failed[\s\S]*\.ai-action-progress-time[^{]*\{[^}]*ui-monospace/, "Schemer must retain readable success and failure durations on proposal cards");
for (const stateContract of [/root\.inert = !open/, /aria-hidden/, /aria-expanded/]) assert.match(shared, stateContract, "the shared drawer must synchronize inert and ARIA state");

console.log("Schemer AI isolation and action contracts passed");
