pid /tmp/nginx.pid;
error_log /dev/stderr notice;

events {
    worker_connections 256;
}

http {
    access_log /dev/stdout;
    server_tokens off;
    client_body_temp_path /tmp/client-body;
    proxy_temp_path /tmp/proxy;
    fastcgi_temp_path /tmp/fastcgi;
    uwsgi_temp_path /tmp/uwsgi;
    scgi_temp_path /tmp/scgi;
    client_max_body_size 4m;
    resolver 127.0.0.11 valid=10s ipv6=off;

    upstream schemii_backend {
        zone schemii_backend 64k;
        server schemii:8000 resolve;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://schemii_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_read_timeout 30s;
            proxy_send_timeout 30s;
        }
    }
}
