"""Transactional migration behavior against a real disposable PostgreSQL target."""

from dataclasses import dataclass
import os
from typing import Iterator
import uuid

import pytest
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict
from pydantic import SecretStr

from schemii.common.connections.models import (
    PostgresSslMode,
    ResolvedPostgresConnection,
)
from schemii.common.postgres import PsycopgPostgresGateway
from schemii.common.postgres.errors import (
    PostgresMigrationExecutionError,
    PostgresMigrationStaleError,
)
from schemii.common.postgres.models import PostgresCatalog
from tests.integration.postgres_fixture import PostgresMetadataHarness


@dataclass(frozen=True)
class GatewayTarget:
    connection: ResolvedPostgresConnection
    namespace: str


@pytest.fixture
def gateway_target(
    postgres_metadata: PostgresMetadataHarness,
) -> Iterator[GatewayTarget]:
    parameters = conninfo_to_dict(
        postgres_metadata.environment["SCHEMII_METADATA_DSN"]
    )
    database = parameters.get("dbname")
    username = parameters.get("user")
    assert database
    assert username
    namespace = f"gateway_it_{uuid.uuid4().hex}"
    target = GatewayTarget(
        connection=ResolvedPostgresConnection(
            id="pg_" + uuid.uuid4().hex,
            revision=1,
            name="Disposable gateway integration target",
            host=parameters.get("host") or parameters.get("hostaddr") or "localhost",
            port=int(parameters.get("port") or 5432),
            database=database,
            username=username,
            ssl_mode=PostgresSslMode.PREFER,
            connect_timeout=5,
            password=SecretStr(os.environ["SCHEMII_TEST_METADATA_PASSWORD"]),
        ),
        namespace=namespace,
    )
    with postgres_metadata.connection_factory() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(namespace))
            )
        connection.commit()
    try:
        yield target
    finally:
        with postgres_metadata.connection_factory() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL("DROP SCHEMA {} CASCADE").format(
                        sql.Identifier(namespace)
                    )
                )
            connection.commit()


def _table(catalog: PostgresCatalog, name: str):
    return next((table for table in catalog.tables if table.name == name), None)


def test_execute_migration_requires_reviewed_fingerprint_and_returns_commit_evidence(
    gateway_target: GatewayTarget,
) -> None:
    gateway = PsycopgPostgresGateway()
    namespace = gateway_target.namespace
    connection = gateway_target.connection
    baseline = gateway.introspect(connection, namespace)
    stale_events: list[str] = []

    with pytest.raises(PostgresMigrationStaleError) as stale:
        gateway.execute_migration(
            connection,
            namespace,
            "0" * 64,
            [f"CREATE TABLE {namespace}.must_not_exist (id bigint PRIMARY KEY)"],
            on_started=lambda _transaction_id, _identity: stale_events.append("started"),
            on_intended=lambda _catalog: stale_events.append("intended"),
        )

    assert stale.value.current_fingerprint == baseline.fingerprint
    assert stale_events == []
    after_stale = gateway.introspect(connection, namespace)
    assert after_stale.fingerprint == baseline.fingerprint
    assert _table(after_stale, "must_not_exist") is None

    events: list[tuple[str, object]] = []
    result = gateway.execute_migration(
        connection,
        namespace,
        baseline.fingerprint,
        [
            (
                f"CREATE TABLE {namespace}.committed_widgets "
                "(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "label text NOT NULL)"
            ),
            (
                f"CREATE INDEX committed_widgets_label_idx "
                f"ON {namespace}.committed_widgets (label)"
            ),
        ],
        on_started=lambda transaction_id, identity: events.append(
            ("started", (transaction_id, identity))
        ),
        on_intended=lambda catalog: events.append(
            ("intended", catalog.fingerprint)
        ),
    )

    assert [kind for kind, _ in events] == ["started", "intended"]
    assert events[0][1] == (result.transaction_id, result.target_identity)
    assert events[1][1] == result.catalog.fingerprint
    assert result.completed_step_count == 2
    assert result.target_identity["database"] == connection.database
    assert result.transaction_id.isdigit()
    assert gateway.transaction_status(connection, result.transaction_id) == "committed"
    intended_table = _table(result.catalog, "committed_widgets")
    assert intended_table is not None
    assert [index.name for index in intended_table.indexes] == [
        "committed_widgets_label_idx"
    ]

    visible = gateway.introspect(connection, namespace)
    assert visible.fingerprint == result.catalog.fingerprint
    assert _table(visible, "committed_widgets") is not None


def test_failed_multi_step_migration_rolls_back_every_target_statement(
    gateway_target: GatewayTarget,
) -> None:
    gateway = PsycopgPostgresGateway()
    namespace = gateway_target.namespace
    connection = gateway_target.connection
    baseline = gateway.introspect(connection, namespace)
    started: list[tuple[str, dict[str, object]]] = []
    intended: list[PostgresCatalog] = []

    with pytest.raises(PostgresMigrationExecutionError) as failed:
        gateway.execute_migration(
            connection,
            namespace,
            baseline.fingerprint,
            [
                f"CREATE TABLE {namespace}.partial_table (id bigint PRIMARY KEY)",
                (
                    f"CREATE INDEX partial_table_missing_idx "
                    f"ON {namespace}.partial_table (missing_column)"
                ),
            ],
            on_started=lambda transaction_id, identity: started.append(
                (transaction_id, identity)
            ),
            on_intended=intended.append,
        )

    assert failed.value.completed_step_count == 1
    assert len(started) == 1
    transaction_id, identity = started[0]
    assert transaction_id.isdigit()
    assert identity["database"] == connection.database
    assert intended == []
    assert gateway.transaction_status(connection, transaction_id) == "aborted"

    visible = gateway.introspect(connection, namespace)
    assert visible.fingerprint == baseline.fingerprint
    assert _table(visible, "partial_table") is None
