"""Transactional migration behavior against a real disposable PostgreSQL target."""

from dataclasses import dataclass
import os
from typing import Iterator
import uuid

import pytest
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict
from pydantic import SecretStr

from schemii.common.connections.models import (
    PostgresSslMode,
    ResolvedPostgresConnection,
)
from schemii.common.postgres import PsycopgPostgresGateway
from schemii.common.postgres.errors import (
    PostgresMigrationExecutionError,
    PostgresMigrationPreconditionError,
    PostgresMigrationStaleError,
)
from schemii.common.postgres.models import PostgresCatalog
from tests.integration.postgres_fixture import PostgresMetadataHarness


@dataclass(frozen=True)
class GatewayTarget:
    connection: ResolvedPostgresConnection
    namespace: str


@pytest.fixture
def gateway_target(
    postgres_metadata: PostgresMetadataHarness,
) -> Iterator[GatewayTarget]:
    parameters = conninfo_to_dict(
        postgres_metadata.environment["SCHEMII_METADATA_DSN"]
    )
    database = parameters.get("dbname")
    username = parameters.get("user")
    assert database
    assert username
    namespace = f"gateway_it_{uuid.uuid4().hex}"
    target = GatewayTarget(
        connection=ResolvedPostgresConnection(
            id="pg_" + uuid.uuid4().hex,
            revision=1,
            name="Disposable gateway integration target",
            host=parameters.get("host") or parameters.get("hostaddr") or "localhost",
            port=int(parameters.get("port") or 5432),
            database=database,
            username=username,
            ssl_mode=PostgresSslMode.PREFER,
            connect_timeout=5,
            password=SecretStr(os.environ["SCHEMII_TEST_METADATA_PASSWORD"]),
        ),
        namespace=namespace,
    )
    with postgres_metadata.connection_factory() as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(namespace))
            )
        connection.commit()
    try:
        yield target
    finally:
        with postgres_metadata.connection_factory() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    sql.SQL("DROP SCHEMA {} CASCADE").format(
                        sql.Identifier(namespace)
                    )
                )
            connection.commit()


def _table(catalog: PostgresCatalog, name: str):
    return next((table for table in catalog.tables if table.name == name), None)


def test_execute_migration_requires_reviewed_fingerprint_and_returns_commit_evidence(
    gateway_target: GatewayTarget,
) -> None:
    gateway = PsycopgPostgresGateway()
    namespace = gateway_target.namespace
    connection = gateway_target.connection
    baseline = gateway.introspect(connection, namespace)
    stale_events: list[str] = []

    with pytest.raises(PostgresMigrationStaleError) as stale:
        gateway.execute_migration(
            connection,
            namespace,
            "0" * 64,
            [f"CREATE TABLE {namespace}.must_not_exist (id bigint PRIMARY KEY)"],
            on_started=lambda _transaction_id, _identity: stale_events.append("started"),
            on_intended=lambda _catalog: stale_events.append("intended"),
        )

    assert stale.value.current_fingerprint == baseline.fingerprint
    assert stale_events == []
    after_stale = gateway.introspect(connection, namespace)
    assert after_stale.fingerprint == baseline.fingerprint
    assert _table(after_stale, "must_not_exist") is None

    events: list[tuple[str, object]] = []
    result = gateway.execute_migration(
        connection,
        namespace,
        baseline.fingerprint,
        [
            (
                f"CREATE TABLE {namespace}.committed_widgets "
                "(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "label text NOT NULL)"
            ),
            (
                f"CREATE INDEX committed_widgets_label_idx "
                f"ON {namespace}.committed_widgets (label)"
            ),
        ],
        on_started=lambda transaction_id, identity: events.append(
            ("started", (transaction_id, identity))
        ),
        on_intended=lambda catalog: events.append(
            ("intended", catalog.fingerprint)
        ),
    )

    assert [kind for kind, _ in events] == ["started", "intended"]
    assert events[0][1] == (result.transaction_id, result.target_identity)
    assert events[1][1] == result.catalog.fingerprint
    assert result.completed_step_count == 2
    assert result.target_identity["database"] == connection.database
    assert result.transaction_id.isdigit()
    recovery = gateway.transaction_status(connection, result.transaction_id)
    assert recovery.status == "committed"
    assert recovery.target_identity == result.target_identity
    intended_table = _table(result.catalog, "committed_widgets")
    assert intended_table is not None
    assert [index.name for index in intended_table.indexes] == [
        "committed_widgets_label_idx"
    ]

    visible = gateway.introspect(connection, namespace)
    assert visible.fingerprint == result.catalog.fingerprint
    assert _table(visible, "committed_widgets") is not None


def test_failed_multi_step_migration_rolls_back_every_target_statement(
    gateway_target: GatewayTarget,
) -> None:
    gateway = PsycopgPostgresGateway()
    namespace = gateway_target.namespace
    connection = gateway_target.connection
    baseline = gateway.introspect(connection, namespace)
    started: list[tuple[str, dict[str, object]]] = []
    intended: list[PostgresCatalog] = []

    with pytest.raises(PostgresMigrationExecutionError) as failed:
        gateway.execute_migration(
            connection,
            namespace,
            baseline.fingerprint,
            [
                f"CREATE TABLE {namespace}.partial_table (id bigint PRIMARY KEY)",
                (
                    f"CREATE INDEX partial_table_missing_idx "
                    f"ON {namespace}.partial_table (missing_column)"
                ),
            ],
            on_started=lambda transaction_id, identity: started.append(
                (transaction_id, identity)
            ),
            on_intended=intended.append,
        )

    assert failed.value.completed_step_count == 1
    assert len(started) == 1
    transaction_id, identity = started[0]
    assert transaction_id.isdigit()
    assert identity["database"] == connection.database
    assert intended == []
    recovery = gateway.transaction_status(connection, transaction_id)
    assert recovery.status == "aborted"
    assert recovery.target_identity == identity

    visible = gateway.introspect(connection, namespace)
    assert visible.fingerprint == baseline.fingerprint
    assert _table(visible, "partial_table") is None


def test_required_column_empty_table_precondition_is_rechecked_under_lock(
    gateway_target: GatewayTarget,
    postgres_metadata: PostgresMetadataHarness,
) -> None:
    gateway = PsycopgPostgresGateway()
    namespace = gateway_target.namespace
    connection = gateway_target.connection
    initial = gateway.introspect(connection, namespace)
    created = gateway.execute_migration(
        connection,
        namespace,
        initial.fingerprint,
        [f"CREATE TABLE {namespace}.guarded_events (id bigint PRIMARY KEY)"],
        on_started=lambda _transaction_id, _identity: None,
        on_intended=lambda _catalog: None,
    )
    assert gateway.table_emptiness(connection, namespace, ["guarded_events"]) == {
        "guarded_events": True
    }

    with postgres_metadata.connection_factory() as direct:
        with direct.cursor() as cursor:
            cursor.execute(
                sql.SQL("INSERT INTO {}.guarded_events (id) VALUES (1)").format(
                    sql.Identifier(namespace)
                )
            )
        direct.commit()

    with pytest.raises(PostgresMigrationPreconditionError) as caught:
        gateway.execute_migration(
            connection,
            namespace,
            created.catalog.fingerprint,
            [
                f"ALTER TABLE {namespace}.guarded_events "
                "ADD COLUMN tenant_id bigint NOT NULL"
            ],
            on_started=lambda _transaction_id, _identity: None,
            on_intended=lambda _catalog: None,
            required_empty_tables=["guarded_events"],
        )

    assert caught.value.tables == ("guarded_events",)
    visible = gateway.introspect(connection, namespace)
    table = _table(visible, "guarded_events")
    assert table is not None
    assert [column.name for column in table.columns] == ["id"]


def test_incremental_console_preserves_empty_metadata_commands_and_exact_once_dml(
    gateway_target: GatewayTarget, postgres_metadata: PostgresMetadataHarness,
) -> None:
    from schemii.common.postgres.console.gateway import execute_console_statements

    gateway = PsycopgPostgresGateway()
    connection = gateway._connect(gateway_target.connection)
    namespace = gateway_target.namespace
    try:
        results = execute_console_statements(connection, [
            f"CREATE TABLE {namespace}.incremental_marker (id integer PRIMARY KEY, visits integer)",
            f"INSERT INTO {namespace}.incremental_marker VALUES (1, 0) RETURNING id",
            f"UPDATE {namespace}.incremental_marker SET visits = visits + 1 RETURNING visits",
            "SELECT 1::integer AS value WHERE false",
            "SHOW statement_timeout",
            "SELECT 1.25::numeric, DATE '2026-09-29', decode('abcd', 'hex'), '{\"x\":1}'::jsonb",
        ])
        assert [result.command for result in results] == ["CREATE", "INSERT", "UPDATE", "SELECT", "SHOW", "SELECT"]
        assert results[1].rows == ((1,),)
        assert results[2].rows == ((1,),)
        assert results[3].rows == ()
        assert [(column.name, column.data_type) for column in results[3].columns] == [("value", "integer")]
        assert results[5].rows == (("1.25", "2026-09-29", "\\xabcd", {"x": 1}),)
        connection.commit()
        with postgres_metadata.connection_factory() as observer:
            with observer.cursor() as cursor:
                cursor.execute(sql.SQL("SELECT visits FROM {}.incremental_marker WHERE id = 1").format(sql.Identifier(namespace)))
                assert cursor.fetchone()["visits"] == 1
    finally:
        connection.close()
    assert gateway._connection_capacity._total == 0


@pytest.mark.parametrize(("rows", "width", "cell_limit", "limit_name"), [
    (100_000, 8, 256 * 1024, "console.results.page_memory_bytes"),
    (100_000, 8192, 256 * 1024, "console.results.page_memory_bytes"),
    (2, 512 * 1024, 256 * 1024, "console.results.maximum_cell_bytes"),
])
def test_incremental_console_caps_real_results_and_restores_protocol(
    gateway_target: GatewayTarget, rows, width, cell_limit, limit_name,
) -> None:
    from schemii.common.postgres.console.gateway import execute_console_statements
    from schemii.common.postgres.errors import PostgresConsoleLimitError

    gateway = PsycopgPostgresGateway()
    connection = gateway._connect(gateway_target.connection)
    try:
        with pytest.raises(PostgresConsoleLimitError) as caught:
            execute_console_statements(connection, [
                f"SELECT repeat('x', {width}) FROM generate_series(1, {rows})",
            ], maximum_result_bytes=16384, maximum_cell_bytes=cell_limit)
        assert caught.value.limit_name == limit_name
        assert caught.value.observed > caught.value.limit
        connection.rollback()
        assert execute_console_statements(connection, ["SELECT 1 AS healthy"])[0].rows == ((1,),)
    finally:
        connection.close()
    assert gateway._connection_capacity._total == 0


def test_incremental_returning_limit_rolls_back_whole_script_without_replay(
    gateway_target: GatewayTarget, postgres_metadata: PostgresMetadataHarness,
) -> None:
    from schemii.common.postgres.console.gateway import execute_console_statements
    from schemii.common.postgres.errors import PostgresConsoleLimitError

    namespace = gateway_target.namespace
    with postgres_metadata.connection_factory() as setup:
        with setup.cursor() as cursor:
            cursor.execute(sql.SQL("CREATE TABLE {}.returning_marker (id integer PRIMARY KEY, visits integer); CREATE SEQUENCE {}.dispatch_marker").format(
                sql.Identifier(namespace), sql.Identifier(namespace)))
            cursor.execute(sql.SQL("INSERT INTO {}.returning_marker SELECT n, 0 FROM generate_series(1, 1000) AS n").format(sql.Identifier(namespace)))
        setup.commit()
    gateway = PsycopgPostgresGateway()
    connection = gateway._connect(gateway_target.connection)
    try:
        with pytest.raises(PostgresConsoleLimitError) as caught:
            execute_console_statements(connection, [
                f"UPDATE {namespace}.returning_marker SET visits = visits + 1 WHERE id = 1",
                f"UPDATE {namespace}.returning_marker SET visits = visits + 1 RETURNING nextval('{namespace}.dispatch_marker'), repeat('x', 1024)",
                f"UPDATE {namespace}.returning_marker SET visits = 100",
            ], maximum_result_bytes=4096)
        assert caught.value.statement_index == 1
        connection.rollback()
        with postgres_metadata.connection_factory() as observer:
            with observer.cursor() as cursor:
                cursor.execute(sql.SQL("SELECT sum(visits) AS visits FROM {}.returning_marker").format(sql.Identifier(namespace)))
                assert cursor.fetchone()["visits"] == 0
                # Sequence calls survive rollback. The write ran at most once;
                # cancellation may stop it before all source rows were visited.
                cursor.execute(sql.SQL("SELECT last_value FROM {}.dispatch_marker").format(sql.Identifier(namespace)))
                assert 1 <= cursor.fetchone()["last_value"] <= 1000
        assert execute_console_statements(connection, ["SELECT 1"])[0].rows == ((1,),)
    finally:
        connection.close()
    assert gateway._connection_capacity._total == 0


def test_named_read_wide_page_carries_one_row_without_skipping(
    gateway_target: GatewayTarget,
) -> None:
    gateway = PsycopgPostgresGateway()
    session = gateway.open_console_read_session(
        gateway_target.connection, gateway_target.namespace,
        ["SELECT n, repeat('x', 8192) FROM generate_series(1, 6) AS n ORDER BY n"],
        on_started=lambda pid: True, page_memory_bytes=16384,
    )
    try:
        received = []
        for offset in range(6):
            page = session.page(0, offset, 1000)
            assert len(page) == 1
            assert page[0][1] == "x" * 8192
            assert len(session._readers[0].pending) <= 1
            received.append(page[0][0])
        assert received == [1, 2, 3, 4, 5, 6]
        assert session.page(0, 6, 1000) == ()
    finally:
        session.close()
    assert gateway._connection_capacity._total == 0
