import { readFile, stat } from 'node:fs/promises';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { randomBytes } from 'node:crypto';

/** Config selection is synchronous; setup validates the private manifest itself. */
export function accountStorageState(env = process.env, fallback = './artifacts/playwright-auth/admin.json') {
  const manifest = env.SCHEMII_E2E_PARALLEL_ACCOUNTS_FILE;
  const index = env.SCHEMII_E2E_PROCESS_INDEX;
  if (!manifest && !index) return fallback;
  if (!manifest || !isAbsolute(manifest) || !['1', '2'].includes(index)) {
    throw new Error('Parallel browser authentication requires an absolute accounts manifest and process index 1 or 2.');
  }
  return join(dirname(manifest), `process-${index}`, 'auth.json');
}

/** Existing accounts are only used when the test operator explicitly supplies credentials. */
export async function accountCredentials(env = process.env) {
  if (env.SCHEMII_E2E_PARALLEL_ACCOUNTS_FILE || env.SCHEMII_E2E_PROCESS_INDEX) {
    accountStorageState(env);
    if (env.SCHEMII_E2E_USERNAME || env.SCHEMII_E2E_PASSWORD || env.SCHEMII_E2E_CREDENTIALS_FILE) {
      throw new Error('Parallel browser accounts cannot be combined with another credential selector.');
    }
    const { readParallelAccounts } = await import('./parallel-account.js');
    const manifest = await readParallelAccounts(env.SCHEMII_E2E_PARALLEL_ACCOUNTS_FILE);
    const account = manifest.accounts[Number(env.SCHEMII_E2E_PROCESS_INDEX) - 1];
    return { username: account.username, password: account.password };
  }
  if (env.SCHEMII_E2E_USERNAME || env.SCHEMII_E2E_PASSWORD) {
    if (!env.SCHEMII_E2E_USERNAME || !env.SCHEMII_E2E_PASSWORD) {
      throw new Error('Set both SCHEMII_E2E_USERNAME and SCHEMII_E2E_PASSWORD for browser authentication.');
    }
    return { username: env.SCHEMII_E2E_USERNAME, password: env.SCHEMII_E2E_PASSWORD };
  }
  if (!env.SCHEMII_E2E_CREDENTIALS_FILE) return null;
  const path = env.SCHEMII_E2E_CREDENTIALS_FILE;
  const info = await stat(path);
  if (!info.isFile() || (info.mode & 0o077)) throw new Error('The browser credentials file must be private (chmod 600).');
  const document = JSON.parse(await readFile(path, 'utf8'));
  const credentials = document.admin || document;
  if (typeof credentials.username !== 'string' || !credentials.username || typeof credentials.password !== 'string' || !credentials.password) {
    throw new Error('The browser credentials file requires username and password, optionally nested under admin.');
  }
  return { username: credentials.username, password: credentials.password };
}

/** The original serial login/bootstrap boundary, also used by explicit preparation. */
export async function authenticateBrowserAccount(context, env = process.env) {
  const statusResponse = await context.get('/api/v1/auth/status');
  if (!statusResponse.ok()) throw new Error(`Cannot check browser account authentication (HTTP ${statusResponse.status()}).`);
  const status = await statusResponse.json();
  if (!status.enabled) return { identity: null, credentials: null };
  let credentials = await accountCredentials(env);
  let response;
  if (status.setup_required) {
    if (env.SCHEMII_E2E_PARALLEL_ACCOUNTS_FILE || env.SCHEMII_E2E_PROCESS_INDEX) {
      throw new Error('Parallel browser accounts must already be prepared; first-account setup is serial.');
    }
    if (env.SCHEMII_E2E_BOOTSTRAP !== '1') throw new Error('First account setup requires explicit SCHEMII_E2E_BOOTSTRAP=1.');
    const directory = env.SCHEMII_SECRET_DIRECTORY || resolve('.schemii/secrets');
    const setupToken = (await readFile(resolve(directory, 'account_setup_token'), 'utf8')).trim();
    if (!setupToken) throw new Error('Browser setup requires the account setup token generated by ./start.sh.');
    credentials ||= { username: `e2e_admin_${randomBytes(6).toString('hex')}`, password: randomBytes(32).toString('base64url') };
    response = await context.post('/api/v1/auth/setup', { data: {
      setup_token: setupToken, ...credentials, display_name: 'Browser test administrator',
    } });
  } else {
    if (!credentials) throw new Error('This installation already has accounts. Set SCHEMII_E2E_USERNAME and SCHEMII_E2E_PASSWORD, or explicitly opt in with SCHEMII_E2E_CREDENTIALS_FILE.');
    response = await context.post('/api/v1/auth/login', { data: credentials });
  }
  if (!response.ok()) throw new Error(`Browser account authentication failed (HTTP ${response.status()}).`);
  const identity = await response.json();
  if (!identity.is_admin) throw new Error('Browser fixtures require an administrator test account.');
  return { identity, credentials };
}
