"""Deterministic database-independent design exports."""

from __future__ import annotations

import hashlib
import json

from .models import SchemiiDesign, SchemiiDesignExport, SchemiiDesignExportRequest


def _quote(identifier: str) -> str:
    return f'"{identifier.replace(chr(34), chr(34) * 2)}"'


def _statement(value: str) -> str:
    return value.strip().rstrip(";")


def _postgresql_sql(design: SchemiiDesign, include_drops: bool) -> str:
    content = design.content
    lines = [
        "-- Generated by Schemii from saved desired state.",
        f"-- Workspace: {design.workspace_id}",
        f"-- Design revision: {design.revision}",
        f"-- Design fingerprint: {design.fingerprint}",
        "",
    ]
    if include_drops:
        for view in reversed(content.views):
            kind = "MATERIALIZED VIEW" if view.kind == "materialized_view" else "VIEW"
            lines.append(f"DROP {kind} IF EXISTS {_quote(view.name)} CASCADE;")
        for routine in reversed(content.functions):
            kind = "PROCEDURE" if routine.kind == "procedure" else "FUNCTION"
            lines.append(
                f"DROP {kind} IF EXISTS {_quote(routine.name)}({routine.arguments.strip()}) CASCADE;"
            )
        for table in reversed(content.tables):
            lines.append(f"DROP TABLE IF EXISTS {_quote(table.name)} CASCADE;")
        if content.tables or content.views or content.functions:
            lines.append("")

    table_by_id = {table.id: table for table in content.tables}
    column_by_id = {
        column.id: column
        for table in content.tables
        for column in table.columns
    }
    for table in content.tables:
        definitions: list[str] = []
        for column in table.columns:
            parts = [_quote(column.name), column.data_type.strip()]
            if column.generated_expression is not None:
                parts.append(
                    f"GENERATED ALWAYS AS ({column.generated_expression.strip()}) STORED"
                )
            elif column.identity is not None:
                identity = "ALWAYS" if column.identity == "always" else "BY DEFAULT"
                parts.append(f"GENERATED {identity} AS IDENTITY")
            elif column.default_expression is not None:
                parts.append(f"DEFAULT {column.default_expression.strip()}")
            if not column.nullable:
                parts.append("NOT NULL")
            definitions.append("    " + " ".join(parts))
        for key in table.keys:
            columns = ", ".join(_quote(column_by_id[column_id].name) for column_id in key.column_ids)
            kind = "PRIMARY KEY" if key.kind == "primary" else "UNIQUE"
            definitions.append(f"    CONSTRAINT {_quote(key.name)} {kind} ({columns})")
        for check in table.checks:
            definitions.append(
                f"    CONSTRAINT {_quote(check.name)} CHECK ({check.expression.strip()})"
            )
        body = ",\n".join(definitions)
        lines.extend([f"CREATE TABLE {_quote(table.name)} (", body, ");", ""])

    for relationship in content.relationships:
        source = table_by_id[relationship.source_table_id]
        target = table_by_id[relationship.target_table_id]
        source_columns = ", ".join(
            _quote(column_by_id[column_id].name)
            for column_id in relationship.source_column_ids
        )
        target_columns = ", ".join(
            _quote(column_by_id[column_id].name)
            for column_id in relationship.target_column_ids
        )
        statement = (
            f"ALTER TABLE {_quote(source.name)} ADD CONSTRAINT {_quote(relationship.name)} "
            f"FOREIGN KEY ({source_columns}) REFERENCES {_quote(target.name)} ({target_columns}) "
            f"ON UPDATE {relationship.on_update} ON DELETE {relationship.on_delete}"
        )
        if relationship.deferrable:
            statement += " DEFERRABLE"
            if relationship.initially_deferred:
                statement += " INITIALLY DEFERRED"
        lines.extend([statement + ";", ""])

    for table in content.tables:
        for index in table.indexes:
            entries = [
                _quote(column_by_id[column_id].name)
                for column_id in index.column_ids
            ]
            if index.expression:
                entries.append(index.expression.strip())
            unique = "UNIQUE " if index.unique else ""
            statement = (
                f"CREATE {unique}INDEX {_quote(index.name)} ON {_quote(table.name)} "
                f"USING {_quote(index.method)} ({', '.join(entries)})"
            )
            if index.predicate:
                statement += f" WHERE {index.predicate.strip()}"
            lines.extend([statement + ";", ""])

    for routine in content.functions:
        lines.extend([_statement(routine.definition) + ";", ""])
    for view in content.views:
        kind = "MATERIALIZED VIEW" if view.kind == "materialized_view" else "VIEW"
        lines.extend(
            [f"CREATE {kind} {_quote(view.name)} AS", _statement(view.definition) + ";", ""]
        )
    return "\n".join(lines).rstrip() + "\n"


def export_design(
    design: SchemiiDesign,
    request: SchemiiDesignExportRequest,
) -> SchemiiDesignExport:
    """Compile exactly one saved design revision without target I/O."""

    if request.format == "schemii_json":
        document = {
            "formatVersion": 1,
            "workspaceId": design.workspace_id,
            "designRevision": design.revision,
            "fingerprint": design.fingerprint,
            "content": design.content.model_dump(mode="json", by_alias=True),
        }
        content = json.dumps(
            document,
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        ) + "\n"
        extension = "json"
        media_type = "application/json"
    else:
        content = _postgresql_sql(design, request.include_drop_statements)
        extension = "sql"
        media_type = "application/sql"
    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
    return SchemiiDesignExport(
        workspace_id=design.workspace_id,
        design_revision=design.revision,
        file_name=f"schemii-{design.workspace_id}-r{design.revision}.{extension}",
        media_type=media_type,
        content=content,
        sha256=digest,
    )
