"""Shared PostgreSQL read-only authority gateway."""

from .errors import (
    PostgresCatalogLimitError,
    PostgresCatalogValidationError,
    PostgresConnectionError,
    PostgresDatabaseMismatchError,
    PostgresDriverUnavailableError,
    PostgresGatewayError,
    PostgresInvalidNamespaceError,
    PostgresNamespaceNotFoundError,
    PostgresQueryError,
)
from .gateway import (
    MAX_CONNECT_TIMEOUT_SECONDS,
    PostgresCatalogLimits,
    PostgresGateway,
    PsycopgPostgresGateway,
)
from .models import (
    PostgresCatalog,
    PostgresCheckConstraint,
    PostgresColumn,
    PostgresConnectionTestResult,
    PostgresExclusionConstraint,
    PostgresForeignKeyRelationship,
    PostgresFunction,
    PostgresIndex,
    PostgresMaterializedView,
    PostgresNotNullConstraint,
    PostgresPrimaryKey,
    PostgresTable,
    PostgresTrigger,
    PostgresUniqueConstraint,
    PostgresView,
    compute_catalog_fingerprint,
)
from .query_analysis import (
    QueryDefinitionError,
    analyze_query_definition,
    parse_query_definition,
    referenced_relations,
)
from .query_models import QueryAnalysis

__all__ = [
    "MAX_CONNECT_TIMEOUT_SECONDS",
    "PostgresCatalog",
    "PostgresCatalogLimitError",
    "PostgresCatalogLimits",
    "PostgresCatalogValidationError",
    "PostgresCheckConstraint",
    "PostgresColumn",
    "PostgresConnectionError",
    "PostgresConnectionTestResult",
    "PostgresExclusionConstraint",
    "PostgresDatabaseMismatchError",
    "PostgresDriverUnavailableError",
    "PostgresForeignKeyRelationship",
    "PostgresFunction",
    "PostgresGateway",
    "PostgresGatewayError",
    "PostgresIndex",
    "PostgresInvalidNamespaceError",
    "PostgresMaterializedView",
    "PostgresNamespaceNotFoundError",
    "PostgresNotNullConstraint",
    "PostgresPrimaryKey",
    "PostgresQueryError",
    "PostgresTable",
    "PostgresTrigger",
    "PostgresUniqueConstraint",
    "PostgresView",
    "PsycopgPostgresGateway",
    "QueryAnalysis",
    "QueryDefinitionError",
    "analyze_query_definition",
    "compute_catalog_fingerprint",
    "parse_query_definition",
    "referenced_relations",
]
